---
- name: stop firewall
  shell: systemctl stop firewalld

- name: disable firewall when boot up
  shell: systemctl disable firewalld

- name: stop selinux
  shell: sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config

- name: setenforce 0
  shell: setenforce 0
